info:
  description: ''
  title: ''
  version: ''
openapi: 3.0.0
paths:
  /annotator/:
    get:
      operationId: annotator_list
      tags:
      - annotator
  /annotator/annotation{format}:
    get:
      operationId: annotator_read
      parameters:
      - in: path
        name: format
        required: true
        schema:
          description: ''
          title: ''
          type: string
      - in: query
        name: status
        schema:
          description: ''
          title: ''
          type: string
      - in: query
        name: segment
        schema:
          description: ''
          title: ''
          type: string
      tags:
      - annotator
    post:
      operationId: annotator_create
      parameters:
      - in: path
        name: format
        required: true
        schema:
          description: ''
          title: ''
          type: string
      tags:
      - annotator
  /annotator/audioannotation{format}:
    get:
      operationId: annotator_read_0
      parameters:
      - in: path
        name: format
        required: true
        schema:
          description: ''
          title: ''
          type: string
      - in: query
        name: status
        schema:
          description: ''
          title: ''
          type: string
      - in: query
        name: segment
        schema:
          description: ''
          title: ''
          type: string
      tags:
      - annotator
    post:
      operationId: annotator_create_0
      parameters:
      - in: path
        name: format
        required: true
        schema:
          description: ''
          title: ''
          type: string
      tags:
      - annotator
  /annotator/corpus{format}:
    get:
      description: List all corpora, or create a new corpus.
      operationId: annotator_read_1
      parameters:
      - in: path
        name: format
        required: true
        schema:
          description: ''
          title: ''
          type: string
      tags:
      - annotator
    post:
      description: List all corpora, or create a new corpus.
      operationId: annotator_create_1
      parameters:
      - in: path
        name: format
        required: true
        schema:
          description: ''
          title: ''
          type: string
      tags:
      - annotator
  /annotator/model{format}:
    get:
      operationId: annotator_read_2
      parameters:
      - in: path
        name: format
        required: true
        schema:
          description: ''
          title: ''
          type: string
      - in: query
        name: status
        schema:
          description: ''
          title: ''
          type: string
      - in: query
        name: tags
        schema:
          description: ''
          title: ''
          type: string
      tags:
      - annotator
    post:
      operationId: annotator_create_2
      parameters:
      - in: path
        name: format
        required: true
        schema:
          description: ''
          title: ''
          type: string
      tags:
      - annotator
  /annotator/segment{format}:
    get:
      description: List all segments, or create a new segment
      operationId: annotator_read_3
      parameters:
      - in: path
        name: format
        required: true
        schema:
          description: ''
          title: ''
          type: string
      - in: query
        name: corpus
        schema:
          description: ''
          title: ''
          type: string
      tags:
      - annotator
    post:
      description: List all segments, or create a new segment
      operationId: annotator_create_3
      parameters:
      - in: path
        name: format
        required: true
        schema:
          description: ''
          title: ''
          type: string
      tags:
      - annotator
  /annotator/spantextannotation{format}:
    get:
      operationId: annotator_read_4
      parameters:
      - in: path
        name: format
        required: true
        schema:
          description: ''
          title: ''
          type: string
      - in: query
        name: status
        schema:
          description: ''
          title: ''
          type: string
      - in: query
        name: segment
        schema:
          description: ''
          title: ''
          type: string
      tags:
      - annotator
    post:
      operationId: annotator_create_4
      parameters:
      - in: path
        name: format
        required: true
        schema:
          description: ''
          title: ''
          type: string
      tags:
      - annotator
  /annotator/textannotation{format}:
    get:
      operationId: annotator_read_5
      parameters:
      - in: path
        name: format
        required: true
        schema:
          description: ''
          title: ''
          type: string
      - in: query
        name: status
        schema:
          description: ''
          title: ''
          type: string
      - in: query
        name: segment
        schema:
          description: ''
          title: ''
          type: string
      tags:
      - annotator
    post:
      operationId: annotator_create_5
      parameters:
      - in: path
        name: format
        required: true
        schema:
          description: ''
          title: ''
          type: string
      tags:
      - annotator
  /annotator{format}:
    get:
      operationId: read
      parameters:
      - in: path
        name: format
        required: true
        schema:
          description: ''
          title: ''
          type: string
  /users/:
    get:
      operationId: users_list
      parameters:
      - in: query
        name: page
        schema:
          description: A page number within the paginated result set.
          title: Page
          type: integer
      tags:
      - users
  /users/{id}/:
    get:
      operationId: users_read
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this user.
          title: ID
          type: integer
      tags:
      - users
  /users/{id}{format}:
    get:
      operationId: users_read_0
      parameters:
      - in: path
        name: format
        required: true
        schema:
          description: ''
          title: ''
          type: string
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this user.
          title: ID
          type: integer
      tags:
      - users
  /users{format}:
    get:
      operationId: read_0
      parameters:
      - in: path
        name: format
        required: true
        schema:
          description: ''
          title: ''
          type: string
servers:
- url: ''
