# Generated by Django 2.1.7 on 2019-08-05 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='segment',
            new_name='a_segment',
        ),
        migrations.RenameField(
            model_name='corpus',
            old_name='owner',
            new_name='c_owner',
        ),
        migrations.RenameField(
            model_name='segment',
            old_name='corpus',
            new_name='s_corpus',
        ),
    ]
