# Generated by Django 2.1.7 on 2019-08-05 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0002_auto_20190805_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='a_segment',
            new_name='segment',
        ),
        migrations.RenameField(
            model_name='corpus',
            old_name='c_owner',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='segment',
            old_name='s_corpus',
            new_name='corpus',
        ),
    ]
