# Generated by Django 2.1.5 on 2022-11-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0010_auto_20221123_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='log_file',
            field=models.CharField(default='', help_text='log file path', max_length=10000),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='model_path',
            field=models.CharField(default='', help_text='model file / dir path', max_length=10000),
        ),
    ]
